apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: bastion
  project: btd

resources:
- statefulset.yml
- configmap.yml
- rbac.yaml
- sa.yaml
  #- ../../../_common
  #- service.yml

  #secretGenerator:
  #- files:
  #- kubeconfig.yml
  #name: bastion-kubeconfig

generatorOptions:
  disableNameSuffixHash: true
