- name: Download yq
  get_url:
    url: "https://github.com/mikefarah/yq/releases/download/{{ YQ_VERSION }}/yq_linux_amd64"
    dest: "/tmp"
    force: yes

- name: Move yq binary
  command: mv /tmp/yq_linux_amd64 /usr/bin/yq
  changed_when: False

- name: change right for yq
  ansible.builtin.file:
    path: "/usr/bin/yq"
    owner: root
    mode: '0777'
