apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: bastion

namespace: observability


resources:
- manifests
- ingressroute.yaml

images:
- name: bastion
  newName: registry.gitlab.tech.orange/businesstalkdigital/integration/tools/bastion:1.2
