apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: toolaccess
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: user
subjects:    
- kind: ServiceAccount
  name: toolaccess

