- name: Get temporary file
  tempfile:
    state: file
    suffix: .tar.gz
  register: tmp_file

- name: Download kubens
  get_url:
    url: "https://github.com/ahmetb/kubectx/releases/download/{{ KUBENS_VERSION }}/kubens_{{ KUBENS_VERSION }}_linux_x86_64.tar.gz"
    dest: "{{ tmp_file.path }}"
    force: yes

- name: Extract kubens binary
  unarchive:
    src: "{{ tmp_file.path }}"
    copy: no
    dest: /tmp
    exclude: [ README.md, LICENSE ]
    mode: 0755

- name: Remove temporary file
  file:
    path: "{{ tmp_file.path }}"
    state: absent

- name: Move kubens binary
  command: mv /tmp/kubens /usr/bin/kubens
  changed_when: False
- name: Get temporary file
  tempfile:
    state: file
    suffix: .tar.gz
  register: tmp_file

- name: Get temporary file
  tempfile:
    state: file
    suffix: .tar.gz
  register: tmp_file

- name: Download kubctx
  get_url:
    url: "https://github.com/ahmetb/kubectx/releases/download/{{ KUBCTX_VERSION }}/kubectx_{{ KUBECTX_VERSION }}_linux_x86_64.tar.gz"
    dest: "{{ tmp_file.path }}"
    force: yes

- name: Extract kubectx binary
  unarchive:
    src: "{{ tmp_file.path }}"
    copy: no
    dest: /tmp
    exclude: [ README.md, LICENSE ]
    mode: 0755

- name: Remove temporary file
  file:
    path: "{{ tmp_file.path }}"
    state: absent

- name: Move kubectx binary
  command: mv /tmp/kubectx /usr/bin/kubectx
  changed_when: False
