- name: Check presence of kubens {{ KUBEENS_VERSION }}
  stat:
    path: /usr/bin/kubens
  register: kubens

- include_tasks:
    file: download_kubens.yml
  when: not kubens.stat.exists
  
- name: Setup default kubens symlink
  file:
    path: /usr/bin/kubens
    state: link
    src: kubens
    force: True
  when: KUBENS_DEFAULT

- name: Check presence of kubectx {{ KUBECTX_VERSION }}
  stat:
    path: /usr/bin/kubectx
  register: kubectx

- include_tasks:
    file: download_kubens.yml
  when: not kubectx.stat.exists

- name: Setup default kubctx symlink
  file:
    path: /usr/bin/kubctx
    state: link
    src: kubectx
    force: True
  when: KUBECTX_DEFAULT
