- name: Get temporary file
  tempfile:
    state: file
    suffix: .gz
  register: tmp_file

- name: Download kubewire
  get_url:
    url: https://github.com/postfinance/kubewire/releases/download/v0.1.0/kubewire_v0.1.0_linux_amd64.gz
    dest: "{{ tmp_file.path }}"
    force: yes

- name: Extract kubewire binary
  shell: "gzip -dc {{ tmp_file.path }} >/usr/bin/kubewire && chmod 755 /usr/bin/kubewire"
  changed_when: False

- name: Remove temporary file
  file:
    path: "{{ tmp_file.path }}"
    state: absent
