apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: prod

namespace: cpaas-tool

resources:
- ../base

configMapGenerator:
- behavior: merge
  envs:
  - urls.env
  name: bastion

images:
- name: bastion
  newName: dockerfactory.tech.orange/cpaas/bastion
  newTag: "3.3"
