apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: btd

resources:
- ../base

configMapGenerator:
- behavior: merge
  envs:
  - urls.env
  name: bastion

  #newTag: latest
images:
- name: bastion
  newName: btd-ols-virt-docker-stable.repos.tech.orange/bastion
  newTag: 2ce93f298ebf969fd927bf14dfa3d76523c9c2e7
